### ISSUE TITLE
Do we need bots and shared folders?

### ISSUE THREAD

**Issue by GalochkinKirov** [OAGr/foretold#104]

**Comment by OAGr** [comment]
Can you describe this a bit more?

**Comment by GalochkinKirov** [comment]
![Screenshot_20190416_161852.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/a8988580-2174-4972-8605-26716c3927b0)

In Foretold project we have two strange folders, for what are they?

**Comment by OAGr** [comment]
Oh yeah, go ahead and delete them. They're not being used now.
