### ISSUE TITLE
Clicking the arrows on the calendar widget doesn't work.

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#136]
Step 1: Click "New Measurable" on a relevant page. (Top right)
![image](https://user-images.githubusercontent.com/377065/56460839-17b2f780-63a1-11e9-8d4a-9576bf1eff1b.png)

Step 2: Open calendar, click arrow in top-right
![image](https://user-images.githubusercontent.com/377065/56460836-0cf86280-63a1-11e9-8a10-1ad52d4eb67a.png)

**Comment by GalochkinKirov** [comment]
![Screenshot_20190520_140041.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/1d06f235-6fcf-498e-9c2b-ff67fec65e58)

It seems like it works now

**Comment by OAGr** [comment]
Yea, I think you're right.
