### ISSUE TITLE
Refactor permissions naming

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#150]
See comments:
https://github.com/OAGr/foretold/pull/149

Please post a suggested set of names in a comment for review, before refactoring.

**Comment by GalochkinKirov** [comment]
Please, take a look at list below:
```bots.isOwner -> botBelongsToCurrentUser
isInChannel -> currentAgentInChannel
isMoreThenOneAdmin -> channelHasMultipleAdmins
isSubjectAsObject -> membershipBelongsToCurrentAgent
isObjectAdmin -> membershipHasAdminRole
measurable.isOwner -> measurableBelongsToCurrentAgent
measurable.isArchived -> measurableIsArchived```

**Comment by OAGr** [comment]
In general looks good.

I think that
"measurableBelongsToCurrentAgent" isn't specific enough, because there could be multiple relationships. Maybe ""measurableIsOwnedByCurrentAgent"?

**Comment by GalochkinKirov** [comment]
"measurableIsOwnedByCurrentAgent", we should think within the context of a request, and there is only one measurable. It is not about associations. 


channelHasMembershipWithCurrentAgent - good for me

**Comment by GalochkinKirov** [comment]
ok
