### ISSUE TITLE
Get "measurements" to get CDF

### ISSUE THREAD

**Issue by GalochkinKirov** [OAGr/foretold#163]
For each "measurable" get all "measurements" (in one query) with "type=competitive". For each of "measurements" to get CDF value , create new "measurement" with "type=aggregation" and "taggedMeasurementId". See "server/src/bots/primary.js" for instance and base point.

**Comment by OAGr** [comment]
Note that I don't think we should actually make an aggregation for every single measurement, so the taggedMeasurementId may not be needed (or we just tag the most recent measurement). While aggregating on each competitive measurement may be ideal, it could be really expensive, so just doing it for every hour most seems safer for a first step.

**Comment by GalochkinKirov** [comment]
So we are going to make aggregation for the previous "measurements"? Not in a recursive approach as it is now in "server/src/bots/primary.js"?

What the algorithm is?

**Comment by GalochkinKirov** [comment]
What the algorithm is?

**Comment by GalochkinKirov** [comment]
And the main question, why the previous solution ("server/src/bots/primary.js") makes aggregation each time for each "measurement" if it did that in a previous running? Since data are sorted by date.

**Comment by OAGr** [comment]
You're right; the new version should not do it for every single measurement, but instead in batches every hour. If there were 20 measurements in that hour, they will collectively just get one aggregation.

**Comment by OAGr** [comment]
The previous solution ("primary.js") was experimental, but after some thinking I don't think we should do the same strategy.

**Comment by OAGr** [comment]
Don't worry about the algorithm for now. Just return some test data, like a fake CDF or the first measurement value.

**Comment by GalochkinKirov** [comment]
@OAGr So we should aggregate last measurements only? Let say within current hour?

**Comment by OAGr** [comment]
We should fetch all the measurements we will need (the last measurement of every competitive agent on that measurable), but the ``aggregate`` function (assuming one is made as a placeholder) should just make a measurement of default data.
