### ISSUE TITLE
Do we need primary.js file anymore?

### ISSUE THREAD

**Issue by GalochkinKirov** [OAGr/foretold#170]
Remove "server/src/bots/primary.js" file.

**Comment by GalochkinKirov** [comment]
What's about "server/src/services/measurable/MakeAggregation.js" file? Do we need it?

**Comment by OAGr** [comment]
Yea, the two bot files that exist are now obsolete. Feel free to delete.

**Comment by GalochkinKirov** [comment]
Will use as base point for a short time, then will remove files.

**Comment by OAGr** [comment]
sounds good
