### ISSUE TITLE
Measurables should have a ``resultOrLatestMeasurement(agentId)`` attribute, that returns a measurement.

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#189]
It takes the ID of an aggregation agent, in practice.

Rules:
- If the measureable is in the ``CLOSED`` state, return the most recent ``OBJECTIVE`` measurement. If this doesn't exist, raise an error (This should always exist; it's how it get closed. 
- If the measurable is not in the CLOSED state, look for the most recent measurement for it by the agent in question. Return it if it exists. If it doesn't exist, return nothing.

**Comment by GalochkinKirov** [comment]
I have put "resultOrLatestMeasurement" right into "Measurement" attribute of "Measurable" type. Think it is more convenience.

**Comment by OAGr** [comment]
Can you explain what you mean a bit more? The ``Measurable`` type has a ``Measurements`` attribute; do you mean you are using this with a filter? Can you write down the graphQL API to be a bit more precise?

**Comment by GalochkinKirov** [comment]
For instance 
```{ 
	measurable (
		id: "9e10db1b-7201-4086-a16b-86bac7b3f19a"
	) { 
		Measurement (
			resultOrLatestMeasurementForAgentId: "a8a88fc2-b484-7966-a782-dae3c3d8724e"
		) { 
			id 	
			competitorType 
			agentId
		}
	    
	}
}```

Will it be ok or not?
