### ISSUE TITLE
The aggregation bot ``tags`` it's aggregate appropriately.

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#197]
[This requires #195 and #196]

After the bot gets the correct queries, and finds an aggregate, it submits it correctly.

The bot is making an aggregate that corresponds with, say, measurement #883.

```
measurementCreate(input: 
{
  value: ...,
  competitorType: AGGREGATIVE,
  relevantAt: [createdAt date of #883]
  taggedMeasurementId: #883
}
)
```

**Comment by GalochkinKirov** [comment]
competitorType: AGGREGATION?

**Comment by OAGr** [comment]
Yes, good catch.
