### ISSUE TITLE
Refactor: data.js files 

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#20]
- Separate authorizaton logic into separate file/library
- Change ``Sequelize.UUIDV4`` to ``DataTypes.UUIDV1`` or similar. 

![image](https://user-images.githubusercontent.com/377065/54025419-5fcfdf00-4192-11e9-9aef-9c3daad96ca2.png)

**Comment by GalochkinKirov** [comment]
@OAGr What do you mean "Provide better errors"?
