### ISSUE TITLE
The user "Bots" page should only show bots by that specific user.

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#258]
Right now users see all bots.

This will probably require a few things:
1) The "bots" query on the server should accept an "ownerId" param for filtering.
2) There should be a new GraphQL query in the client that calls this, with the ownerID of the current user.

**Comment by OAGr** [comment]
Go here for the bots page:

![image](https://user-images.githubusercontent.com/377065/58804354-925e6c00-8609-11e9-8e1f-2adbbcc64a99.png)

**Comment by OAGr** [comment]
Gr... After trying it out, I think there's been a miscommunication. The story title isn't that great. 

Users should be able to see the bots of all users. However, on a user's page, only that user's bots should be shown. So when I go to "Bob23"s page, I should see all of "Bob23's" bots. Previously, this page would show all of the bots by all users, which was just a bug.

**Comment by GalochkinKirov** [comment]
Ok, going to fix it
