### ISSUE TITLE
Invite Agent Page: Change table to use FC.Table 

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#276]
Right now the Invite Agents page shows an Ant.design table with pagination. Instead it should just show one long table, using FC.Table. It's header should be styled like that in the "/channels" page.

**Comment by GalochkinKirov** [comment]
Page example, leave it here for me:
![Screenshot_20190618_090904.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/d81817f6-06ab-4b90-9778-37a850ccdb1a)
