### ISSUE TITLE
Can't create a prediction (submit button greyed out)

### ISSUE THREAD

**Issue by brachbach** [OAGr/foretold#282]
<img width="1918" alt="Screen Shot 2019-06-16 at 5 46 17 PM" src="https://user-images.githubusercontent.com/16952006/59572021-00ba1a00-905f-11e9-9f27-8d07654664e0.png">

https://www.foretold.io/c/2a6f08ab-6471-48e2-9cfd-7e398b93f8a0

**Comment by OAGr** [comment]
Predictions can't be exact numbers. They must be distributions.

The problem here is that the error isn't clear.
