### ISSUE TITLE
Condition a log normal distribution to be greater than zero

### ISSUE THREAD

**Issue by Jsevillamol** [OAGr/foretold#286]
I want to set a log normal probability distribution over the positive real numbers, that is, I want to have a lognormal distribution conditioned on x > 0. Can I do that with the current version?

**Comment by OAGr** [comment]
Lognormal distributions by default can't go to 0 or less. In the future we could do similar things to other kinds of distributions, but not yet.

**Comment by Jsevillamol** [comment]
I feel confused. What is showing on my screen now when I type an input like "0 to 80"?

**Comment by Jsevillamol** [comment]
Ahh I see. If the first number is 0 the resulting distribution is normal, not lognormal

**Comment by OAGr** [comment]
Yea, exactly. 0 isn't valid in a lognormal distribution (at least, as anything other than the 0th percentile)
