### ISSUE TITLE
Measurable Page with Url

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#300]
Right now, there's no way to get a URL for a measurable, because they don't have unique URLs. Instead, there should be a page for these.

Steps:
1) Routes like, "https://www.foretold.io/c/channelId/m/measurableId" should load that corresponding measurable, outside of a measurable index reducer/view. This means there would be no pagination or "back" button", but everything else would look the same.

2) When using the pagination to view a specific measurable, the URL should be changed to the one used for #1, in case the user wants to refresh their page or send the link to someoene else.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/40ba6480-4e21-4b9a-85ee-ebb89d4ff5e9)
Feel free to split this into two stories if desired.

**Comment by GalochkinKirov** [comment]
![Screenshot_20190627_121426.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/64705982-14cc-4066-b271-761df41a0002)

Changing "pagination reducer" to support dynamic URLs is hard and takes a lot of time (there should be something as re-hydration mechanism to recovery state from URL params), I propose just to place link "to measurable page" which will change router URL without breaking another parts of application.

@OAGr

**Comment by OAGr** [comment]
That's fine. I'll mess with it a bit.
