### ISSUE TITLE
Email epic issues / bugs

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#368]
These are for the epic/emails branch.

1. When I try making a new account via a custom email and password, I see errors around username validations. 

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/16c36bfb-f17f-4643-9022-41a2991a0ecd)

In the console, it says, 
``"'Validation error: Validation isAlphanumeric on name failed,\nValidation error: Validation len on name failed'"``

Note that there are some cases where the auth0 username will be invalid. In these cases, just save the name as blank.

2. I haven't gotten it to save my picture. It seems like that's blank. 

3. Spaces shouldn't be allowed in usernames.

4. In user-data, ``updateUserInfo`` should be renamed to ``updateUserInfoFromAuth0`` or similar, because it is a very specific set of info. (Regular updates should be different, I assume).

**Comment by GalochkinKirov** [comment]
1. Done.
2. Done.
3. Done.
4. Done.
