### ISSUE TITLE
Integrate React-Popper to show hover-overs around lightbulb icons.

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#37]
This should probably involve wrapping some of React-Popper or similar with Reasonml.
https://github.com/FezVrasta/react-popper

![image](https://user-images.githubusercontent.com/377065/54309853-f5230700-45c8-11e9-8373-6e138a12aaff.png)

The content in the hover doesn't matter, I can change that.

**Comment by GalochkinKirov** [comment]
![Screenshot_20190520_121941.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/14050c50-5370-4bd9-88a8-10ac2b305be3)
