### ISSUE TITLE
Email External Provider

### ISSUE THREAD

**Issue by RomanGalochkin** [OAGr/foretold#376]
We set up a mail system (Sendgrid or Mailgun, I assume), preferably with Heroku, so it works on multiple environments nicely.

- Set up Dev/Prod env for email external system,

**Comment by GalochkinKirov** [comment]
@OAGr Please, provide credentials of S3 SES (host, port, user, password)?

**Comment by GalochkinKirov** [comment]
Email provider credentials are set in Heroku.
