### ISSUE TITLE
Adds client routes to support emails subscribers

### ISSUE THREAD

**Issue by RomanGalochkin** [OAGr/foretold#379]
1. Create new email boxes for "Help", "Subscribe" Emails from users, admin@example.com
2. Link for "unsubscribe": https://foretold.com/unsubscribe?token={{token}}
3. Link for "subscribe": https://foretold.com/subscribe?token={{token}}

**Comment by OAGr** [comment]
What happens when someone subscribes or unsubscribes? Does this change the “stopAllEmails” flag?

**Comment by RomanGalochkin** [comment]
For simplest way for now it is just a route to "Preferences" page.

**Comment by OAGr** [comment]
sg, thanks
