### ISSUE TITLE
use env instead of hardcoded urls and other settings in frontend

### ISSUE THREAD

**Issue by Wirnex** [OAGr/foretold#38]

**Comment by OAGr** [comment]
How urgent is this? Also, can you try this? It's not too hard.

**Comment by Wirnex** [comment]
It's not a big rush.

**Comment by OAGr** [comment]
@Wirnex Was this done in this PR? Can we close this issue?
https://github.com/OAGr/foretold/pull/39

**Comment by Wirnex** [comment]
yes @OAGr we can close it
