### ISSUE TITLE
Backups for Production & Staging versions

### ISSUE THREAD

**Issue by RomanGalochkin** [OAGr/foretold#394]
- Cron & Bash
- Or external services, or custom bash script
- To isolate backups
- Rotate backups

**Comment by RomanGalochkin** [comment]
No huge rush because I do it myself on my computer.

**Comment by OAGr** [comment]
Can you use Heroku PostgreSQL automatic backups, perhaps?

**Comment by RomanGalochkin** [comment]
Thanks. It was done some time back.

Useful commands:
# Download DB capture
heroku pg:backups:capture -a prediction-backend
heroku pg:backups:download -a prediction-backend

heroku pg:backups:capture -a prediction-backend-staging
heroku pg:backups:download -a prediction-backend-staging

# To list backups
heroku pg:backups --app prediction-backend
heroku pg:backups --app prediction-backend-staging
heroku pg:backups:info b017 --app prediction-backend

# To add schedule for a default DB URL:
heroku pg:backups:schedule --at '02:00 America/Los_Angeles' --app prediction-backend
heroku pg:backups:schedule --at '02:00 America/Los_Angeles' --app prediction-backend-staging

# To see schedule:
heroku pg:backups:schedules --app prediction-backend
heroku pg:backups:schedules --app prediction-backend-staging

**Comment by RomanGalochkin** [comment]
![Screenshot_20190726_101121.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/85028981-e57d-4638-8819-74409536c537)

**Comment by OAGr** [comment]
Nice, thanks!
