### ISSUE TITLE
Serve the application client with the server, automatically

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#4]
Currently, Heroku only serves the server. It should also serve the client. This could be either done via setting up a separate Heroku application, or by having the server code serve the client code. 

Tasks:
- Get this setup working on Heroku, where the client is under a Heroku Url.
- Notify Ozzie, who will modify name.com so that this Url is used for foretold.io

**Comment by Wirnex** [comment]
Do we also need to serve the client in PRs and master?

**Comment by OAGr** [comment]
It would be preferable. I imagine it won't be that hard, if it's done in one repo. Happy to make it a separate story if it's additional work.

**Comment by Wirnex** [comment]
No need for a separate story hopefully.
