### ISSUE TITLE
Measurable Query: Judgement_Pending Support

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#40]
- The server should return "Judgement_Pending" state for measurables. This is true when the database state is OPEN and the ``expectedResolutionDate`` is after the current time.
- The ``measurables`` query should accept a parameter for ``states``, which accepts a list of acceptable states to return. It should only return these states.
- The ``measurables`` query should order responses first by their state.

**Comment by GalochkinKirov** [comment]
```- Modify the graphQL output to add the “Pending_Review” state.
- When querying measurables, one could specify an array of possible states. Only these are queried server-side.
- The standard way of sorting is by sorting in that order. ```
