### ISSUE TITLE
Archived channels should have an "Archived" label

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#419]
This would make it obvious which are archived.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/6356ac43-71b3-45f2-8271-620c7957d940)

**Comment by RomanGalochkin** [comment]
![Screenshot_20190725_131035.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/eff28b77-3c4c-4283-aeb7-9c47bf4e1125)
