### ISSUE TITLE
Channels: GraphQL Spec

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#43]
Specify the GraphQL API for channels, upon completion of the epic.

**Comment by GalochkinKirov** [comment]
@OAGr What does this issue mean? Does it relate to channels external interfaces?

**Comment by OAGr** [comment]
This was basically a part of this: https://github.com/OAGr/foretold/issues/6
It meant that I wanted an outline of what the API would have looked like, once the channel epic was done. It doesn't seem necessary now.
