### ISSUE TITLE
Development Documentation for Terms, Processes, Data descriptions and determinations 

### ISSUE THREAD

**Issue by RomanGalochkin** [OAGr/foretold#442]
To add a file in the root of repository with the name like "Knowledge" or similar, and place there following categories of knowledge about the system of the application:
- Common System Description
-- Application Pattern Name "3 layer pattern" (UI, Server Side application, Application State)
- Objects (describe objects):
-- Agent is an abstraction of User, and Bot objects
-- Measurable is a Question of probability
-- and so on
- Terms
-- Authorization
-- Authentication
-- Identification
-- User Binding - is process of binding users via email with Auth0 and the system
- Server Side Application Archecture
-- Layers (Data, Models and so on)
-- Middlewares, Authorizers
-- Async / Sync Flows Descriptions 
- External System Requirements
-- Auth0
-- AWS SES
- Server Side Application Requirements
-- Heroku as SaaS
-- Backup / Restore 
-- Platform Description (Node.js)
-- DBS name and version
- User Use-cases
and others points which have a sense to give to any developer or a man to quickly get "an representation" of system

**Comment by RomanGalochkin** [comment]
It will help us to remember all main aspects of applications in time.

**Comment by RomanGalochkin** [comment]
I have already added "Application.md" file, and will add something to this step by step.

**Comment by OAGr** [comment]
Sounds good! Feel free to prioritize this task as you wish.
