### ISSUE TITLE
Figure out: Community Updates

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#444]
We should have a page with a list of all the updates within a community. This should feature:
- New measurements
- New members
- New questions

This should ideally have pagination.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/2009d0c6-852c-4f60-bd39-0adbb17aed8e)

Come up with a proposal for how this could work, and estimate the total number of points you think a first version would be.

**Comment by RomanGalochkin** [comment]
I propose to make "News Subsystem" which will include the following flow: 
1. Server Side (2 points at least): 
- System Event ("new member", "new measurements", "new question", and so on) ---> triggers of News Subsystem ---> new row of "News table". Here I am sure that a dynamic data is a bad practice. 
- new API
2. Client (2 points at least): 
- table with pagination
- page

**Comment by OAGr** [comment]
Sounds good. How about we call that table the "Update table" instead of "News table". Agree it should be a table.

**Comment by OAGr** [comment]
Can you make stories for this? We could then close this specific task.

**Comment by RomanGalochkin** [comment]
Sure
