### ISSUE TITLE
fix seeds

### ISSUE THREAD

**Issue by Wirnex** [OAGr/foretold#45]
I can't migrate and seed without an error on an empty database
`ERROR: null value in column "auth0Id" violates not-null constraint`

**Comment by GalochkinKirov** [comment]
Do we really need "seeds"? Because supporting of "seeds" it is like time wasting on this stage.
@OAGr 
@Wirnex

**Comment by OAGr** [comment]
Yea, agreed. If you need it, fine, but I don't need it personally.

**Comment by Wirnex** [comment]
Not an emergency but let’s keep the task
