### ISSUE TITLE
[FeedItems, Server]: Prepare Server Part of the epic

### ISSUE THREAD

**Issue by RomanGalochkin** [OAGr/foretold#451]
- FeedItem Model
- API to get FeedItem through
- First attempt to add Updates

**Comment by RomanGalochkin** [comment]
FeedItem table: id (uuid), channelId (uuid), body (jsonb), createAt(timestamp), updatedAt (timestamp).
AgentFeedItems table: id (uuid), agentId, channelId, readAt, createdAt, updatedAt

**Comment by OAGr** [comment]
Don'y add type(enum ACTION_REQUIRED, INFO, NONE), we may change it later. Also, I'm not sure if we need AgentFeedItems yet or at all (if we show based on the last time they've seen a list)

**Comment by RomanGalochkin** [comment]
Sure, ok
