### ISSUE TITLE
Strange characters in title for emails

### ISSUE THREAD

**Issue by lagerros** [OAGr/foretold#460]
The actual title: 

> Will any actual, somewhat subtantial "collaboration" be seeded/brainstormed/tentatively fleshed out during the retreat and then actual happen?

Was turned into:

> Question "Will any actual, somewhat subtantial &quot;collaboration&quot; be seeded&#x2F;brainstormed&#x2F;tentatively fleshed out during the retreat and then actual happen?" is changed

![image](https://user-images.githubusercontent.com/21347592/62470741-6000f480-b79b-11e9-9433-645d2462e980.png)

**Comment by RomanGalochkin** [comment]
Here is the best solution is to fix templates right in the db:
instead (replaces special characters)
```{{ measurable.name }}```
we should use
```{{{ measurable.name }}}```

@OAGr

**Comment by OAGr** [comment]
Seems pretty simple, I'd say go for it.

**Comment by OAGr** [comment]
ah, got it, this is something for me, will do
