### ISSUE TITLE
Schema and Code Refactor

### ISSUE THREAD

**Issue by Wirnex** [OAGr/foretold#48]
1) strict schema naming entityAction
createMeasurement -> measurementCreate
createSeries -> serieCreate
archiveMeasurable -> measurableArchive
and so on
2) less variety of functions (on our side, not in the schema)
data.measurablesData.archiveMeasurable -> data.measurablesData.updateOne
data.usersData.editUser -> data.usersData.updateOne
3) pull out authentication from the data layer into schema
usersData should not know about getAuth0
4) return a promise from lib/notifications
5) use absolute paths in require with NODE_PATH var
6) use db transactions

**Comment by OAGr** [comment]
I like (1).

I'm hesitant to accept all of (2); I like the idea of having an ``updateOne`` method for most things, but having some specific methods like ``archive`` seems nice. I prefer pushing complexity to the server where possible. 
[This post](https://blog.apollographql.com/designing-graphql-mutations-e09de826ed97) recommends specific mutations, which makes sense to me.

3 Sounds good to me as well.

I think we'll eventually need some other things; like setting up a Relay-style edge/node ontology, for pagination. That could be done separately though, but should be discussed.

**Comment by Wirnex** [comment]
(2) I meant we keep the external interface of the server with specific mutations but have it implemented internally with a standard data layer interface
added 4 and 5 more @OAGr

**Comment by OAGr** [comment]
Oh, makes sense, that sound good to me.

**Comment by GalochkinKirov** [comment]
Tip
createMeasurement -> measurementCreate
createMeasurable -> measurableCreate
createSeries -> seriesCreate
archiveMeasurable -> measurableArchive
unArchiveMeasurable -> measurableUnarchive
editMeasurable -> measurableUpdate
editUser -> userUpdate

**Comment by GalochkinKirov** [comment]
For now, we are not sure about
5) use absolute paths in require with NODE_PATH var
6) use db transactions

This is why we miss it within this PR.

**Comment by OAGr** [comment]
Ok, thanks for mentioning that.
