### ISSUE TITLE
Write document to outline GraphQL Schema

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#6]
As I've discussed with Igor, the GraphQL schema could be more semantic. It would be nice to have a doc to outline what one better version would look like. A google doc may be the best, for commenting.

This outline should not include channels or series; we should probably do that separately

**Comment by OAGr** [comment]
I've been doing some reading on this topic. Some posts I like include:
https://blog.apollographql.com/designing-graphql-mutations-e09de826ed97
https://medium.com/@__xuorig__/graphql-mutation-design-anemic-mutations-dd107ba70496
https://blog.apollographql.com/graphql-schema-design-building-evolvable-schemas-1501f3c59ed5
https://graphqlmastery.com/blog/graphql-best-practices-for-graphql-schema-design

**Comment by OAGr** [comment]
One thing that would be really useful, would be to have pageCount or totalCount as part of a measurable search. Right now we just return the list of measurables, which isn't that great.

**Comment by OAGr** [comment]
Related to the above comment, I think that really, collections/search should be a standard thing. We should be able to do queries like,
```
{ series(id: "ssdfo-8s-jd83-3"}{
    measurables({valueType=["OPEN", "CLOSED"]}) {
       count
       items: {
          id
          name
       }
    }
}}
```

So there would be a level of nesting between ``measurables`` and ``items``, and at this level search queries could be added.

**Comment by OAGr** [comment]
It looks like others use the edge/nodes model, which looks good to me, for doing this sort of thing.
https://blog.apollographql.com/explaining-graphql-connections-c48b7c3d6976
https://github.com/gatsbyjs/gatsby/issues/3962

**Comment by OAGr** [comment]
OneGraph has a similar system
![image](https://user-images.githubusercontent.com/377065/54447701-f62b7400-4741-11e9-8d13-e064939f9c59.png)

**Comment by OAGr** [comment]
![image](https://user-images.githubusercontent.com/377065/54475659-b620cb80-47eb-11e9-9448-e69618314a7e.png)

**Comment by Wirnex** [comment]
thanks
