### ISSUE TITLE
GraphQL Agents/Users/Bots refactor

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#74]
Users & Bots should only be considered aspects of their corresponding agents, as far as the API is concerned. 

Preferred agent API:
```
type Agent {
  id: String!
  type: AgentType!
  name: String
  description: Text
  userAttributes: {
    auth0Id: String!
    bots: Agent
  }
  botAttributes: {
    competitorType: competitorType!
    userAgent: Agent!
  }
  measurementCount: Int!
  channelMemberships: [ChannelsMembership]!
  Measurements: [Measurement]!
  Measurables: Measurable!
  Channels: [Channel]!
}
```

This would probably involve
- Migrations to have name & description fields on the Agent, rather than on users/bots.
- Migrations so that bots have a userAgentId, rather than a userId, which belongs to a agent.
- GraphQL for users/bots can be cleaned up. Both don't need createdAt/updatedAt to be on the graphQL side.

**Comment by GalochkinKirov** [comment]
Well do we have any real reasons to keep association between Bot and User - Agents, why just not keep association Bot -> Agent, User -> Agent? 

I guess that models should be like this
Agent - abstract model
User -> Agent
Bot -> Agent

User is an object who can interact with the system, user is represented with a real man.
Bot is an object represented another programmatic systems.

They can have different fields, but can the same fields.

So I suggest do only these:
1. Remove "userId" field from Bot model. This field is not needed at all I believe. It is redundancy.
2. Do not touch name/descriptions fields of User, Bot.
3. Hide timestamp fields from the Bot/User Interface Definition.

**Comment by GalochkinKirov** [comment]
@OAGr

**Comment by OAGr** [comment]
"Well do we have any real reasons to keep association between Bot and User"
The previous reason was that humans can own bots, but bots can't own other bots. I still think this is the case.

The thing I'm most curious about is the graphQL layer. I think that Agent being an abstract model makes sense on the backend layer, but I'm not sure about graphQL. Union types really seem like what should be done here, but I hear that unions are not always well supported in graphQL and are somewhat discouraged.

Bots need a ``competitorType``, though perhaps it should be renamed ``botType`` or similar. There are a few very different types of bots, this will be fleshed out in future stories.

**Comment by GalochkinKirov** [comment]
"The previous reason was that humans can own bots, but bots can't own other bots. I still think this is the case."
So in this case we should not remove link between Bot and User. This all is ok. And we should not remove Bot and User definitions or hide theirs properties like this:
 ``` userAttributes: {
    auth0Id: String!
    bots: Agent
  }
  botAttributes: {
    competitorType: competitorType!
    userAgent: Agent!
  }```

It is out of the conventions.

**Comment by OAGr** [comment]
Would you recommend doing anything for this, or just leaving things as is?
