### ISSUE TITLE
Available Actions in graphql queries

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#75]
It would be really useful to mirror the permissions in the backend, on the frontend. By this I mean stating them via the graphQL API. 

For instance, on the ``Channel`` query, it could have a property called ``availableActions``, that returns an array of the available items, ``UPDATE``,``CREATE_MEMBERSHIP``, ``JOIN``, and ``LEAVE``. On individual memberships, it would have a similar ``availableActions`` attribute, for things like, ``DELETE`` and ``UPDATE_ROLE``.

These would be customized to the logged in user.

![image.png](https://images.zenhubusercontent.com/5ab55dea4b5806bc2bcc284b/803f1e29-b0ba-49a6-befe-8001e23f786e)

The first story would just be to try this out for the simplest actions on ``Channel``. Later we may want a similar implementation for all the mutation actions.

**Comment by GalochkinKirov** [comment]
@OAGr 
Can we add just another query to get permissions, for instance:
```permissions (channelId: "" measurableId: "") {}```
where channelId or measurableId are optionals, and which will return possible mutations and queries
?

**Comment by OAGr** [comment]
That would also work.

**Comment by GalochkinKirov** [comment]
For now, I have implemented first way for instance:
```
{ 
	permissions (
		channelId: "7150c437-b91c-436c-8fb2-33c65bb028e9"
		measurableId: "7cbf22cb-3fdf-48fd-8f59-5b99512c234d"
	) {
		queries {
			allow
			deny
		}
		
		mutations {
			allow
			deny
		}
	}
}
```

The response will be
```
{
    "data": {
        "permissions": {
            "queries": {
                "allow": [
                    "*"
                ],
                "deny": []
            },
            "mutations": {
                "allow": [
                    "*",
                    "measurementCreate",
                    "seriesCreate",
                    "channelMembershipCreate",
                    "channelMembershipDelete",
                    "channelMembershipRoleUpdate",
                    "channelUpdate",
                    "leaveChannel",
                    "measurableCreate"
                ],
                "deny": [
                    "joinChannel",
                    "measurableArchive",
                    "measurableUnarchive",
                    "measurableUpdate"
                ]
            }
        }
    }
}
```
- It is scalable
- Many systems do like this (for instance Kubernetes)

**Comment by GalochkinKirov** [comment]
![Screenshot_20190411_104623.png](https://images.zenhubusercontent.com/5c813bd94e86d6676799e1f6/fdad5504-aaf6-4f82-be0e-e53e04918136)

**Comment by GalochkinKirov** [comment]
Do not be afraid of many queries it is ok for web systems

**Comment by GalochkinKirov** [comment]
But I want to try to add files into entity definitions

**Comment by OAGr** [comment]
Oh, I see what you mean. The example is useful, and knowing that Kubernetes and similar did this is quite useful (I wasn't aware). 

Still though, eventually doing it in entity definitions would be convenient. 

For example, say I want to look at every measurable in a channel. I'm the owner of some of these, and for these specific ones I could edit or archive them.

The client would perform a ``measurables`` query to get all the measurables, but it would be pretty awkward if we had to do one permissions query for every single measurable. Like, we would first have to get a list of all measurables, then create a new query that would basically be 

```
{ 
	permissions (
		channelId: "7150c437-b91c-436c-8fb2-33c65bb028e9"
		measurableId: "measurabbe1Id"
	) {
		queries {
			allow
			deny
		}
		
		mutations {
			allow
			deny
		}
	}
}
{ 
	permissions (
		channelId: "7150c437-b91c-436c-8fb2-33c65bb028e9"
		measurableId: "measurabbe2Id"
	) {
		queries {
			allow
			deny
		}
		
		mutations {
			allow
			deny
		}
	}
}
{ 
	permissions (
		channelId: "7150c437-b91c-436c-8fb2-33c65bb028e9"
		measurableId: "measurabbe3Id"
	) {
		queries {
			allow
			deny
		}
		
		mutations {
			allow
			deny
		}
	}
}
(repeat for 20 measurables on one page)
```

In the client I'm using, the only straightforward way of doing that would be in the React components, which is pretty awkward. The preferred way is to do everything in one big query, somehow.

**Comment by OAGr** [comment]
One way of doing it in the resources, would just be to follow the same structure of ``permissions`` you mentioned, but having ``permissions`` as a common query on most resources.

**Comment by GalochkinKirov** [comment]
Yes, thanks, got you, doing
