### ISSUE TITLE
Write function to generate API key for each user

### ISSUE THREAD

**Issue by OAGr** [OAGr/foretold#88]
This would probably be a long-running token on Auth0. 
1) Research how to do this with Auth0 and suggest a specific solution. Discuss this as a group.
2) Write a simple function to generate an authentication token that won't expire within 30 days at least.

**Comment by OAGr** [comment]
Do you think we should use auth0 or our own token system for this?

I'm not sure if we're really supposed to use Auth0 here, if they have a decent system set up.

Some possible relevant links:
https://auth0.com/docs/api-auth/dynamic-client-registration

**Comment by GalochkinKirov** [comment]
We are going to get foretold JWT token for Agent by Auth0 each time when it needed. @OAGr How do you think?

**Comment by GalochkinKirov** [comment]
On the staging and prod new env are set.

**Comment by OAGr** [comment]
I think we may be thinking of different things. I was thinking something like what's discussed in task #100.
